# Generated by Django 3.1.5 on 2021-01-15 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_question_admin_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='admin_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='contact_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
