# Generated by Django 3.1.5 on 2021-01-19 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210119_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='message_subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_name',
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
