# Generated by Django 3.1.5 on 2021-01-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210119_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ContactMessage',
        ),
    ]
